#!/usr/bin/env ruby

class NoMessageGivenError < Exception
  def to_s
    "No message given"    
  end
end

class CommitWithBranch
  def initialize
    @argv = ARGV
  end
  
  def run
    raise NoMessageGivenError unless message_given?

    index   = @argv.index("-m")
    message = @argv[index + 1]
    @argv[index + 1] = "\"[#{current_branch}] #{message}\""
    git "commit #{@argv.join(' ')}"
  end
  
  def current_branch
    @current_branch ||= get("git branch").split(/\n/).select { |branch| branch =~ /^\* (.*)/ }[0].match(/^\* (.+)/).captures.first
  end
  
  private

  def git(cmd)
    system "git #{cmd}"
  end
  
  def get(cmd)
    `#{cmd}`
  end
  
  def message_given?
    @argv.include?("-m") && @argv[@argv.index("-m") + 1].to_s.length > 0
  end
end

begin
  CommitWithBranch.new.run  
rescue Exception => e
  puts "Error: " + e.to_s
end
