#!/usr/bin/env ruby

class NoMessageGivenError < Exception
  def to_s
    "No message given"    
  end
end

class CommitWithBranch
  def initialize
    @argv = ARGV
  end
  
  def run
    raise NoMessageGivenError unless message_given?

    index   = @argv.index("-m")
    message = @argv[index + 1]
    @argv[index + 1] = "\"[#{current_branch.upcase}] #{message}\""
    git "git commit #{@argv.join(' ')}"
  end
  
  def current_branch
    get("git branch").split(/\n/).select { |branch| branch =~ /^\* (.*)/ }
    @current_branch ||= $1
  end
  
  private

  def git(cmd)
    system cmd
  end
  
  def get(cmd)
    `#{cmd}`
  end
  
  def message_given?
    @argv.include?("-m")
  end
end

CommitWithBranch.new.run